spring.application.name=FinancialAnalysisML
spring.datasource.url=jdbc:mysql://localhost:3306/santanderbasechallenge
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

# --- Spring Batch ---
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true

# --- Job de Métricas Financeiras ---
financial.analysis.job.insertMetricasFinanceiras.cron=0 0 0 1 * *
financial.analysis.job.insertMetricasFinanceiras.enable=true
financial.analysis.job.insertMetricasFinanceiras.pageSize=200

# --- Job de Classificacao ---
financial.analysis.job.insertClassificacao.cron=0 0 0 1 * *
financial.analysis.job.insertClassificacao.enable=true
financial.analysis.job.insertClassificacao.pageSize=200

# --- Job de Rede Arestas ---
financial.analysis.job.insertRedeArestas.cron=0 0 0 1 * *
financial.analysis.job.insertRedeArestas.enable=true
financial.analysis.job.insertRedeArestas.pageSize=200

# --- Job de Rede Metricas ---
financial.analysis.job.insertRedeMetricas.cron=0 0 0 1 * *
financial.analysis.job.insertRedeMetricas.enable=true
financial.analysis.job.insertRedeMetricas.pageSize=200