spring.application.name=FinancialAnalysisML
spring.datasource.url=jdbc:mysql://localhost:3306/santanderchallenge
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

# --- Spring Batch ---
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# --- Job de Métricas Financeiras ---
financial.analysis.job.insertMetricasFinanceiras.cron=0 */5 * * * *
financial.analysis.job.insertMetricasFinanceiras.enable=true
financial.analysis.job.insertMetricasFinanceiras.pageSize=200